# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('product_code', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('official_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('official_image_url', models.URLField(blank=True)),
                ('ages', models.CharField(blank=True, max_length=255)),
                ('pieces', models.CharField(blank=True, max_length=255)),
                ('marketing_text', models.TextField(blank=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
                'ordering': ('-modified', '-created'),
            },
        ),
    ]
