# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161217_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bricklink_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='official_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='official_review_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='official_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='theme_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
