# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybricks', '0003_auto_20170107_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thing',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
