# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybricks', '0004_auto_20170204_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='sold_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
