# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybricks', '0005_auto_20170204_0819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='MyBrick',
        ),
    ]
