# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0010_auto_20170218_1309'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mybricks', '0008_auto_20170218_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mybrick',
            old_name='product',
            new_name='brickset',
        ),
        migrations.AlterUniqueTogether(
            name='mybrick',
            unique_together=set([('brickset', 'user')]),
        ),
    ]
