# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybricks', '0009_auto_20170218_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mybrickitem',
            old_name='item',
            new_name='mybrick',
        ),
        migrations.RenameField(
            model_name='mybrickrecord',
            old_name='item',
            new_name='mybrick',
        ),
    ]
