# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BricklinkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('new_min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('new_max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('new_average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('used_min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('used_max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('used_average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bricklink_record_set', to='sets.Product')),
            ],
            options={
                'verbose_name': 'Bricklink Record',
            },
        ),
        migrations.CreateModel(
            name='EbayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_item_set', to='sets.Product')),
            ],
            options={
                'verbose_name': 'Ebay Item',
            },
        ),
        migrations.CreateModel(
            name='EbayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('new_min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('new_max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('new_average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('used_min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('used_max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('used_average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_record_set', to='sets.Product')),
            ],
            options={
                'verbose_name': 'Ebay Record',
            },
        ),
    ]
