# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0002_bricklinkrecord_ebayitem_ebayrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bricklinkrecord',
            options={'get_latest_by': 'created', 'ordering': ('-created',), 'verbose_name': 'Bricklink Record'},
        ),
        migrations.AlterModelOptions(
            name='ebayrecord',
            options={'get_latest_by': 'created', 'ordering': ('-created',), 'verbose_name': 'Ebay Record'},
        ),
    ]
