# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0004_auto_20170111_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
