# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0006_ebayitem_available'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='BrickSet',
        ),
    ]
