# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0007_auto_20170218_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brickset',
            old_name='product_code',
            new_name='brick_code',
        ),
    ]
