# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0010_auto_20170218_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brickset',
            options={'verbose_name': 'Brick Set'},
        ),
        migrations.AlterModelOptions(
            name='ebayitem',
            options={'verbose_name': 'eBay Item'},
        ),
        migrations.AlterModelOptions(
            name='ebayrecord',
            options={'get_latest_by': 'created', 'ordering': ('-created',), 'verbose_name': 'ebay Record'},
        ),
    ]
