# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0011_auto_20170220_0053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EbayItem',
            new_name='EbayEntry',
        ),
    ]
