# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0012_auto_20170220_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayentry',
            name='brickset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_entry_set', to='sets.BrickSet'),
        ),
    ]
