# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sets', '0002_bricklinkrecord_ebayitem_ebayrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('owned', models.BooleanField(default=True)),
                ('wish', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sets.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('opened_quantity', models.PositiveIntegerField(default=0)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_set', to='items.Item')),
            ],
            options={
                'verbose_name': 'Item Record',
                'ordering': ('-created',),
                'get_latest_by': 'created',
            },
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('product', 'user')]),
        ),
    ]
