# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('opened', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thing_set', to='items.Item')),
            ],
            options={
                'verbose_name': 'Thing',
            },
        ),
    ]
