# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 01:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('owned_count', models.PositiveIntegerField()),
                ('owned_quantity', models.PositiveIntegerField()),
                ('total_estimated_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_official_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_official_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_buying_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_target_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_target_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_new_min_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_new_max_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_new_average_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_used_min_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_used_max_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_used_average_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_new_min_ebay_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_new_max_ebay_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_new_average_ebay_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_used_min_ebay_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_used_max_ebay_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owned_used_average_ebay_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('target_at', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'target_at',
                'verbose_name': 'Dashboard',
                'ordering': ('-target_at',),
            },
        ),
    ]
