# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_buying_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_count',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_new_average_ebay_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_new_average_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_new_max_ebay_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_new_max_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_new_min_ebay_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_new_min_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_official_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_quantity',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_target_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_used_average_ebay_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_used_average_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_used_max_ebay_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_used_max_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_used_min_ebay_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owned_used_min_price',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='average_estimated_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='average_official_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='average_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='average_target_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='bookmarked_item_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='item_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='item_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='new_average_ebay_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='new_average_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='new_max_ebay_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='new_max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='new_min_ebay_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='new_min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='used_average_ebay_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='used_average_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='used_max_ebay_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='used_max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='used_min_ebay_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='used_min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
