# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170107_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='average_buying_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_buying_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
