# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170107_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='average_buying_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='average_estimated_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='average_official_price',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='average_profit',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='average_target_price',
        ),
    ]
