# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20170111_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='product',
            new_name='brickset',
        ),
    ]
